<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-07">

<title>A Bayesian Causal Analysis of Protected Bike Lane Allocation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-1" id="toc-sec-1" class="nav-link active" data-scroll-target="#sec-1"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-2" id="toc-sec-2" class="nav-link" data-scroll-target="#sec-2"><span class="header-section-number">2</span> Conceptual Framework</a></li>
  <li><a href="#sec-3" id="toc-sec-3" class="nav-link" data-scroll-target="#sec-3"><span class="header-section-number">3</span> Data and Research Design</a>
  <ul class="collapse">
  <li><a href="#spatial-analysis" id="toc-spatial-analysis" class="nav-link" data-scroll-target="#spatial-analysis"><span class="header-section-number">3.1</span> Spatial Analysis</a></li>
  <li><a href="#treatment-variable-t---historical-bikeshare-usage" id="toc-treatment-variable-t---historical-bikeshare-usage" class="nav-link" data-scroll-target="#treatment-variable-t---historical-bikeshare-usage"><span class="header-section-number">3.2</span> Treatment Variable: T - Historical Bikeshare Usage</a></li>
  <li><a href="#outcome-variable-y---protected-bike-lanes" id="toc-outcome-variable-y---protected-bike-lanes" class="nav-link" data-scroll-target="#outcome-variable-y---protected-bike-lanes"><span class="header-section-number">3.3</span> Outcome Variable: Y - Protected Bike Lanes</a></li>
  <li><a href="#confounder-z---population" id="toc-confounder-z---population" class="nav-link" data-scroll-target="#confounder-z---population"><span class="header-section-number">3.4</span> Confounder: Z - Population</a></li>
  </ul></li>
  <li><a href="#sec-4" id="toc-sec-4" class="nav-link" data-scroll-target="#sec-4"><span class="header-section-number">4</span> Econometric / Bayesian Model Specification</a></li>
  <li><a href="#sec-5" id="toc-sec-5" class="nav-link" data-scroll-target="#sec-5"><span class="header-section-number">5</span> Results and Interpretation</a>
  <ul class="collapse">
  <li><a href="#model-summary" id="toc-model-summary" class="nav-link" data-scroll-target="#model-summary"><span class="header-section-number">5.1</span> Model Summary</a></li>
  <li><a href="#interpreting-and-understanding-the-results" id="toc-interpreting-and-understanding-the-results" class="nav-link" data-scroll-target="#interpreting-and-understanding-the-results"><span class="header-section-number">5.2</span> Interpreting and Understanding the Results</a></li>
  </ul></li>
  <li><a href="#sec-6" id="toc-sec-6" class="nav-link" data-scroll-target="#sec-6"><span class="header-section-number">6</span> Discussion and Conclusion</a>
  <ul class="collapse">
  <li><a href="#policy-considerations" id="toc-policy-considerations" class="nav-link" data-scroll-target="#policy-considerations"><span class="header-section-number">6.1</span> Policy Considerations</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.2</span> Limitations</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work"><span class="header-section-number">6.3</span> Future Work</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Bayesian Causal Analysis of Protected Bike Lane Allocation</h1>
<p class="subtitle lead">DSAN 5650: Causal Inference for Computational Social Science</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Jacob Meyer <a href="mailto:jm3756@georgetown.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Georgetown University<br>Data Science and Analytics
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Urban planners and policy analysts frequently debate whether municipal transit infrastructure is deployed in response to grassroots citizen demand or guided by demographic advantages. This paper investigates the allocative mechanisms governing the deployment of protected bike lanes by the District Department of Transportation (DDOT) in Washington, D.C. To overcome identification challenges like simultaneous causality and induced demand, we establish temporal precedence by modeling 2026 bike lane infrastructure outcomes against a normalized baseline of 2017 historical Capital Bikeshare trip volume. Utilizing spatial GIS overlays on 2020 Census blocks and applying advanced fuzzy text-matching algorithms to reconcile longitudinal station registries, we construct a block-level dataset linking historical transit utility with modern urban morphology. We implement a Bayesian Logistic Regression framework via PyMC to estimate the marginal effects of historical usage while controlling for population density. Our empirical results reveal a statistically robust, positive posterior distribution for baseline transit demand, demonstrating that municipal planners prioritize high-utilization corridors. This study provides a replicable causal framework for evaluating efficiency and responsiveness in modern urban transit planning.</p>
  </div>
</div>


</header>


<section id="sec-1" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-1"><span class="header-section-number">1</span> Introduction</h2>
<p>As cities expand protected bicycle infrastructure, a core policy question persists on whether municipal planners allocate lanes based on demonstrated citizen demand, or do socio-economic and political factors drive deployment. Empirically answering this question is complicated by simultaneous causality and the “induced demand” trap—where building a bike lane generates the very ridership used to justify it.</p>
<p>To overcome this, this paper establishes strict temporal precedence. We model protected bike lane outcomes in Washington, D.C., as of 2026 against a normalized baseline of organic Capital Bikeshare trip volume from 2017. Using spatial GIS overlays on 2020 Census blocks and fuzzy text-matching algorithms to reconcile longitudinal station registries, we construct a block-level panel that isolates organic utilitarian demand from post-hoc usage. Employing a Bayesian Logistic Regression framework, our results reveal that historical demand positively predicts infrastructure allocation, even when controlling for population density. This study offers a rigorous causal framework for evaluating municipal resource allocation.</p>
</section>
<section id="sec-2" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-2"><span class="header-section-number">2</span> Conceptual Framework</h2>
<p>Urban infrastructure allocation can be broadly categorized into two competing theoretical models:</p>
<ol type="1">
<li><p>The Utilitarian Efficiency Model: Derived from public economics, this framework assumes that municipal agencies act as benevolent social planners aiming to maximize aggregate societal welfare. Under this model, infrastructure investments are directed toward corridors with the highest demonstrated or projected user demand. By placing protected lanes where cycling volume is already dense, planners minimize traffic conflicts, maximize transit utility, and achieve the highest return on municipal capital expenditure.</p></li>
<li><p>The Political Economy &amp; Wealth Bias Model: Rooted in public choice theory, this perspective posits that municipal resource distribution is heavily influenced by political capital, voter turnout, and socio-economic lobbying. Under this model, infrastructure investments are skewed toward wealthier, higher-income neighborhoods where residents possess the time and organizing power to petition local officials, regardless of whether those corridors represent the city’s highest-utility cycling routes.</p></li>
</ol>
<p>Past empirical literature on active transportation infrastructure has struggled with endogeneity. Standard regression models measuring current bike lane density against current cycling volume fail to address reverse feedback loops. A positive association between infrastructure and usage can reflect two distinct phenomena. Demand can cause infrastructure via responsive planning or vise versa the infrastructure is created which induces demand.</p>
<p>To disentangle these mechanisms, we impose a temporal lag structure. By capturing Capital Bikeshare usage from 2017—a period preceding D.C.’s major protected bike lane expansion—we ensure that our treatment metric <span class="math inline">\(T_i\)</span> is strictly exogenous to bike lane construction completed years later (<span class="math inline">\(Y_i\)</span>). This design allows us to isolate whether baseline utilitarian demand served as an input to modern infrastructure policy.</p>
</section>
<section id="sec-3" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-3"><span class="header-section-number">3</span> Data and Research Design</h2>
<section id="spatial-analysis" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="spatial-analysis"><span class="header-section-number">3.1</span> Spatial Analysis</h3>
<p>We used 2020 Census block polygons within DC as our spatial unit of analysis. Based upon the limitations of traditional latitude and longitude coordinates and to get precise spatial joins, we used Universal Transverse Mercator (UTM) Zone 18N projected coordinate system.</p>
</section>
<section id="treatment-variable-t---historical-bikeshare-usage" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="treatment-variable-t---historical-bikeshare-usage"><span class="header-section-number">3.2</span> Treatment Variable: T - Historical Bikeshare Usage</h3>
<p>To construct a comprehensive baseline of historical cycling demand, we processed a full year of 2017 Capital Bikeshare trip data split across four quarterly CSV files. Evaluating a full calendar year eliminates seasonal variances, such as summer spikes or winter declines in ridership.</p>
<p>Because Capital Bikeshare modernized its backend system and station naming conventions between 2017 and 2026, direct merges using historical station ID numbers resulted in severe data loss. Furthermore, standard exact text string matching yielded a 15.8% failure rate due to street abbreviation mismatches. We worked to correct these down from an initial failure rate of over 30%.</p>
<p>Matched stations were merged with modern geospatial point locations and spatially joined (gpd.sjoin) into their intersecting 2020 Census block polygons. We summed total trip departures (<span class="math inline">\(Starts_i\)</span>) and arrivals (<span class="math inline">\(Ends_i\)</span>) per block to construct the aggregate annual demand metric: <span class="math display">\[T_i = \text{Total Historical Volume}_i = Starts_i + Ends_i\]</span></p>
</section>
<section id="outcome-variable-y---protected-bike-lanes" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="outcome-variable-y---protected-bike-lanes"><span class="header-section-number">3.3</span> Outcome Variable: Y - Protected Bike Lanes</h3>
<p>Using D.C. Open Data bicycle lane shapefiles, we filtered the transportation network for physically protected infrastructure categories (BIKELANE_PROTECTED and BIKELANE_DUAL_PROTECTED). We performed a spatial overlay operation (gpd.overlay), clipping protected lane segments at census block boundaries and calculating the length of each segment in meters. We set Y = 1 for all segments greater than 50 meters of protected bike lane to avoid our dataset being distorted by minor segments.</p>
</section>
<section id="confounder-z---population" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="confounder-z---population"><span class="header-section-number">3.4</span> Confounder: Z - Population</h3>
<p>In our attempt to isolate organic cycling demand from general population density, we pulled in 2020 Census total populations counts for each block as our covariate. We used z-score normalization on both T and Z to enable direct comparisons.</p>
</section>
</section>
<section id="sec-4" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-4"><span class="header-section-number">4</span> Econometric / Bayesian Model Specification</h2>
<p>We used a Bayesian Logistic Regression model to predict the probability (<span class="math inline">\(p_i\)</span>) that a specific Census block received a protected bike lane:</p>
<p><span class="math display">\[Y_i \sim \text{Bernoulli}(p_i)\]</span></p>
<p><span class="math display">\[\text{logit}(p_i) = \alpha + \beta_T X_{T,i} + \beta_Z X_{Z,i}\]</span></p>
<p><span class="math inline">\(X_{T,i}\)</span> is the standardized 2017 bike trip volume in that block. <span class="math inline">\(X_{Z,i}\)</span> is the standardized population density of that block. We used standard, neutral priors (<span class="math inline">\(\text{Normal}(0, 1.5)\)</span>) and ran the model in PyMC across 4 independent simulation chains with a No-U-Turn Sampler algorithm implementation in PyMC.</p>
</section>
<section id="sec-5" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-5"><span class="header-section-number">5</span> Results and Interpretation</h2>
<section id="model-summary" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="model-summary"><span class="header-section-number">5.1</span> Model Summary</h3>
<p>Based upon the below table, our Markov chain Monte Carlo sampling completed cleanly. We achieved <span class="math inline">\(\hat{R}\)</span> statistics of 1.00 as desired.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">ETI (89%) LB</th>
<th style="text-align: center;">ETI (89%) UB</th>
<th style="text-align: center;">Bulk ESS</th>
<th style="text-align: center;">Tail ESS</th>
<th style="text-align: center;"><span class="math inline">\(\hat{R}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_T\)</span></td>
<td style="text-align: center;">0.2235</td>
<td style="text-align: center;">0.0340</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">7484</td>
<td style="text-align: center;">5658</td>
<td style="text-align: center;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{Z[0]}\)</span></td>
<td style="text-align: center;">0.2060</td>
<td style="text-align: center;">0.0419</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">0.27</td>
<td style="text-align: center;">6900</td>
<td style="text-align: center;">5857</td>
<td style="text-align: center;">1.00</td>
</tr>
</tbody>
</table>
</section>
<section id="interpreting-and-understanding-the-results" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="interpreting-and-understanding-the-results"><span class="header-section-number">5.2</span> Interpreting and Understanding the Results</h3>
<p>Because predictors were standardized prior to estimation, the slope coefficients reflect the change in log-odds of protected bike lane allocation per one-standard-deviation increase in the feature.</p>
<ol type="1">
<li>Historical demand: The posterior mean for <span class="math inline">\(\beta_T\)</span> is <span class="math inline">\(0.224\)</span> with SD of 0.0340. Exponentiating this coefficient yields an odds ratio of <span class="math inline">\(e^{0.224} \approx 1.251\)</span>. Holding population density constant, a one-standard-deviation increase in 2017 bikeshare volume increases the odds of a census block containing a protected bike lane by 25.1%. Importantly, our entire 89% posterior density interval sits above zero which provides statistical evidence that pre-existing cycling demand causally predicts infrastructure placement.</li>
<li>Population Density: The posterior mean for <span class="math inline">\(\beta_Z\)</span> is <span class="math inline">\(0.206\)</span> (<span class="math inline">\(SD = 0.042\)</span>), corresponding to an odds ratio of <span class="math inline">\(e^{0.206} \approx 1.229\)</span>. Holding historical demand constant, a one-standard-deviation increase in census block population increases the odds of protected bike lane presence by 22.9%.</li>
</ol>
</section>
</section>
<section id="sec-6" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-6"><span class="header-section-number">6</span> Discussion and Conclusion</h2>
<section id="policy-considerations" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="policy-considerations"><span class="header-section-number">6.1</span> Policy Considerations</h3>
<p>Our findings suggest that municipal transportation planning in Washington, D.C. aligns closely with the Utilitarian Efficiency Model. By proving that 2017 trip volumes causally predict modern protected lane placement, we show that DDOT does not deploy infrastructure arbitrarily. Instead, the capital investments reflect a demand-responsive agency that targets corridors with established utility and higher population densities.</p>
</section>
<section id="limitations" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.2</span> Limitations</h3>
<ol type="1">
<li>Across the nine year period from our 2017 ridership data to now, certain stations were decommissioned or relocated leading to some unmapped holdouts and lost information.</li>
<li>There are many other socio-economic confounders such as income or land-use zoning that could impact the bike demand and the policy choice to add protected bike lanes.</li>
</ol>
</section>
<section id="future-work" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="future-work"><span class="header-section-number">6.3</span> Future Work</h3>
<p>Future work in this area could expand the covariate matrix by including measures of Median Household Income. That would help determine the impact of wealth on the presence of bike lanes since wealthier. Additionally, if there exists a database that shows when protected bike lanes were built in DC, that could allow for a fuller analysis of the conditions preceding the installation of bike lanes in certain areas.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>